# Generated by Django 4.0 on 2021-12-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loai_San_Pham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_ten', models.CharField(default='', max_length=255)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='San_Pham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(default='', max_length=255)),
                ('mo_ta', models.TextField(default='')),
                ('gia', models.IntegerField(default=0)),
                ('trang_thai', models.BooleanField(default=True)),
                ('anh_san_pham', models.URLField(max_length=500)),
                ('loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.loai_san_pham')),
            ],
        ),
        migrations.CreateModel(
            name='Chi_Tiet_San_Pham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='', max_length=255)),
                ('gia', models.IntegerField(default=0)),
                ('khuyen_mai', models.IntegerField(default=0)),
                ('ton_kho', models.IntegerField(default=0)),
                ('trang_thai', models.BooleanField(default=True)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.san_pham')),
            ],
        ),
    ]
