# Generated by Django 4.0 on 2021-12-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='san_pham',
            name='so_luong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='san_pham',
            name='anh_san_pham',
            field=models.ImageField(default=None, upload_to='anh'),
        ),
    ]
