# Generated by Django 4.0 on 2021-12-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_san_pham_so_luong_alter_san_pham_anh_san_pham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='san_pham',
            name='anh_san_pham',
            field=models.ImageField(default=None, upload_to='trangchu/static/anh'),
        ),
    ]
