# Generated by Django 3.2.10 on 2022-01-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0006_alter_san_pham_anh_san_pham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='gia',
            field=models.FloatField(default=0),
        ),
    ]
