# Generated by Django 3.2.10 on 2022-02-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0009_alter_chi_tiet_san_pham_san_pham'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chi_tiet_san_pham',
            old_name='gia',
            new_name='gia_khuyen_mai',
        ),
    ]
