# Generated by Django 3.2.10 on 2022-02-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0010_rename_gia_chi_tiet_san_pham_gia_khuyen_mai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ma_Giam_Gia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giam_gia', models.CharField(default='', max_length=255)),
                ('gia_giam_cua_ma', models.FloatField(default=0)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.san_pham')),
            ],
        ),
    ]
