# Generated by Django 3.2.10 on 2022-03-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0011_ma_giam_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ma_giam_gia',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magiamgia', to='sanpham.san_pham'),
        ),
        migrations.AlterField(
            model_name='san_pham',
            name='loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loai', to='sanpham.loai_san_pham'),
        ),
    ]
