# Generated by Django 3.2.10 on 2022-03-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0012_auto_20220302_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chitietsanpham1', to='sanpham.san_pham'),
        ),
    ]
