# Generated by Django 3.2.10 on 2022-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0014_auto_20220316_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='gia_khuyen_mai',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='khuyen_mai',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='ton_kho',
            field=models.IntegerField(default=None),
        ),
    ]
