# Generated by Django 3.2.10 on 2022-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0015_auto_20220415_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chi_tiet_san_pham',
            name='ton_kho',
        ),
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='gia_khuyen_mai',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chi_tiet_san_pham',
            name='khuyen_mai',
            field=models.IntegerField(default=0),
        ),
    ]
