# Generated by Django 4.0 on 2021-12-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khachhang', '0001_initial'),
        ('giohang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gio_hang',
            name='khac_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khachhang.khach_hang'),
        ),
    ]
