# Generated by Django 3.2.10 on 2022-03-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0003_auto_20220303_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gio_hang',
            old_name='khac_hang',
            new_name='khach_hang',
        ),
    ]
