# Generated by Django 3.2.10 on 2022-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0004_rename_khac_hang_gio_hang_khach_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='gio_hang',
            name='trang_thai',
            field=models.IntegerField(default=0),
        ),
    ]
