# Generated by Django 3.2.10 on 2022-04-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0005_gio_hang_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gio_hang',
            name='trang_thai',
        ),
    ]
