# Generated by Django 4.0 on 2021-12-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dat_Hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_chi_goi', models.CharField(default='', max_length=255)),
                ('trang_thai', models.BooleanField(default=False)),
            ],
        ),
    ]
