# Generated by Django 3.2.10 on 2022-03-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_hang',
            name='hinh_thuc',
            field=models.CharField(default='truc_tiep', max_length=255),
        ),
        migrations.AddField(
            model_name='dat_hang',
            name='thanh_toan',
            field=models.CharField(default='chua_thanh_toan', max_length=255),
        ),
        migrations.AlterField(
            model_name='dat_hang',
            name='trang_thai',
            field=models.CharField(default='', max_length=255),
        ),
    ]
