# Generated by Django 3.2.10 on 2022-03-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0004_auto_20220307_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dat_hang',
            name='dia_chi_goi',
        ),
    ]
