# Generated by Django 3.2.10 on 2022-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0005_remove_dat_hang_dia_chi_goi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat_hang',
            name='trang_thai',
            field=models.CharField(default='chua_xac_nhan', max_length=255),
        ),
    ]
