# Generated by Django 3.2.10 on 2022-03-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0006_alter_dat_hang_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat_hang',
            name='trang_thai',
            field=models.CharField(default='', max_length=255),
        ),
    ]
