# Generated by Django 3.2.10 on 2022-03-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0003_auto_20220303_1129'),
        ('dathang', '0007_alter_dat_hang_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat_hang',
            name='gio_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dathang_giohang', to='giohang.gio_hang'),
        ),
    ]
