# Generated by Django 3.2.10 on 2022-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0008_alter_dat_hang_gio_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_hang',
            name='tongtien',
            field=models.FloatField(default=0),
        ),
    ]
