# Generated by Django 3.2.10 on 2022-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0009_dat_hang_tongtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_hang',
            name='trang_thai_dat_hang',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dat_hang',
            name='trang_thai',
            field=models.IntegerField(default=0),
        ),
    ]
