# Generated by Django 3.2.10 on 2022-04-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0014_auto_20220316_2009'),
        ('dathang', '0010_auto_20220402_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_hang',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.san_pham'),
        ),
    ]
