# Generated by Django 3.2.10 on 2022-04-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0011_dat_hang_san_pham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dat_hang',
            name='san_pham',
        ),
    ]
