# Generated by Django 3.2.10 on 2022-04-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0014_auto_20220316_2009'),
        ('dathang', '0012_remove_dat_hang_san_pham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dat_hang',
            name='hinh_thuc',
        ),
        migrations.RemoveField(
            model_name='dat_hang',
            name='thanh_toan',
        ),
        migrations.RemoveField(
            model_name='dat_hang',
            name='tongtien',
        ),
        migrations.RemoveField(
            model_name='dat_hang',
            name='trang_thai',
        ),
        migrations.RemoveField(
            model_name='dat_hang',
            name='trang_thai_dat_hang',
        ),
        migrations.CreateModel(
            name='Chi_Tiet_Dat_Hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tongtien', models.FloatField(default=0)),
                ('thanh_toan', models.CharField(default='chua_thanh_toan', max_length=255)),
                ('hinh_thuc', models.CharField(default='truc_tiep', max_length=255)),
                ('trang_thai_dat_hang', models.CharField(default='', max_length=255)),
                ('trang_thai', models.IntegerField(default=0)),
                ('id_dat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dathang.dat_hang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.san_pham')),
            ],
        ),
    ]
