# Generated by Django 3.2.10 on 2022-04-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0013_auto_20220403_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chi_tiet_dat_hang',
            name='thanh_toan',
        ),
    ]
