# Generated by Django 3.2.10 on 2022-04-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0014_remove_chi_tiet_dat_hang_thanh_toan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_hang',
            name='hinh_thuc',
            field=models.CharField(default='truc_tiep', max_length=255),
        ),
        migrations.AddField(
            model_name='dat_hang',
            name='tongtien',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dat_hang',
            name='trang_thai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dat_hang',
            name='trang_thai_dat_hang',
            field=models.CharField(default='chua_xac_nhan', max_length=255),
        ),
        migrations.DeleteModel(
            name='Chi_Tiet_Dat_Hang',
        ),
    ]
