# Generated by Django 3.2.10 on 2022-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0015_auto_20220403_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_hang',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dat_hang',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
