# Generated by Django 3.2.10 on 2022-04-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0014_auto_20220316_2009'),
        ('dathang', '0020_auto_20220406_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dat_hang',
            name='gio_hang',
        ),
        migrations.CreateModel(
            name='Chi_Tiet_Dat_Hang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('giam_gia', models.IntegerField(default=0)),
                ('dat_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dathang.dat_hang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.san_pham')),
            ],
        ),
    ]
