# Generated by Django 3.2.10 on 2022-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0021_auto_20220412_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_dat_hang',
            name='giam_gia',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
