# Generated by Django 3.2.10 on 2022-04-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0022_alter_chi_tiet_dat_hang_giam_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chi_tiet_dat_hang',
            name='dat_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_hang', to='dathang.dat_hang'),
        ),
    ]
