"""
Django settings for NienLuan project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from re import T

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%(6mfqu(^4r4bkd-im!aadyzds#-m2prdif7-m570@v5(2$7@b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','banhang','*']


SECURE_SSL_REDIRECT = False
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'dangnhap'
LOGOUT_URL = 'dangxuat'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trangchu',
    'dathang',
    'giohang',
    'khachhang',
    'sanpham',
    'rest_framework',
    'quantri',
    'captcha',
    # dang nhập bằng fb
    'social_django',
    'sslserver',
    # excel
    'import_export',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # dang nhập bằng fb
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'NienLuan.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # dang nhap fb
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect',  # 
            ],
        },
    },
]

WSGI_APPLICATION = 'NienLuan.wsgi.application'
# dang nhap fb
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
)

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nienluannganh',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIR = [
    os.path.join(BASE_DIR, 'static/'),

]
MEDIA_URL = '/trangchu/static/'
MEDIA_ROOT =  os.path.join(BASE_DIR, 'trangchu/static/')

AUTH_USER_MODEL = 'khachhang.Khach_Hang'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# django-recaptcha-2.0.6
RECAPTCHA_PUBLIC_KEY  =  '6LcRzNYdAAAAAEQW7QNfp0DK1bBEFThGwftYyEu-' 
RECAPTCHA_PRIVATE_KEY  =  '6LcRzNYdAAAAAJpSUPIFvORvfqoVUWB14SKo9NYF'

RECAPTCHA_REQUIRED_SCORE  =  0,85


SOCIAL_AUTH_FACEBOOK_KEY = '940619409929205' # ID ứng dụng 
SOCIAL_AUTH_FACEBOOK_SECRET = '9fce4e2c1edd197b750ad2ba495789bf' # Bí mật ứng dụng



SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '682904579917-n10n7sr1gamv0ut4gpoec93k4qn73jtq.apps.googleusercontent.com' # ID ứng dụng 
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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' # Bí mật ứng dụng

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-infor',
    messages.INFO: 'alert-infor',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
#gmail tự động
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'nhuttramtv.vn@gmail.com'
EMAIL_HOST_PASSWORD = 'thachthingocloan'